---
title: Parramatta Seventh-Day Adventist Church
timezone: Australia/Sydney
collections:
  home:
    title: Home
    output: true
  ministries:
    title: Ministries
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
