# Site settings
title: Parramatta Seventh-Day Adventist Church
email: comms@parramattasda.org.au
description: Know God.
url: "http://www.parramattasda.org.au"
facebook_username: parramattasda
instagram_username: parramattasda
github_username:  parramattasda

# Build settings
markdown: kramdown
