---
title: Parramatta Seventh-Day Adventist Church
timezone: Australia/Sydney

collections:
  events:
    title: Events
    output: true
  home:
    title: Home Modules
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true

defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page

# Gems
gems:
- jekyll-seo-tag

# Social networks usernames
social:
- title: Twitter
  url: https://www.twitter.com/parramattasda/
  icon: fa-twitter-square
- title: Facebook
  url: https://www.facebook.com/parramattasda/
  icon: fa-facebook-square
- title: Instagram
  url: https://www.instagram.com/parramattasda/
  icon: fa-instagram
- title: GitHub
  url: https://www.github.com/parramattasda/
  icon: fa-github-square

# Build settings
markdown: kramdown
permalink: pretty
